add ilo support higher than ilo4
CSCfi/ansible-role-hp-firmware-upgrade pull request #24
Opened 2019-02-05 15:47 UTC by FLiPp3r90

https://github.com/CSCfi/ansible-role-hp-firmware-upgrade/issues/23

This isn't tested with ILO5 but works with ILO4.

2019-02-06 09:51 UTC, martbhell requested changes

2019-02-06 09:51 UTC, martbhell commented on tasks/prerequisite.yml
> +    - hponcfg
We do not have hponcfg in the repo we use (fwpp [1]).

So this brings in a dependency on another repo for us, which I'm not a big fan of.

[1]: https://downloads.linux.hpe.com/SDR/project/fwpp/index.html

2019-02-06 09:51 UTC, martbhell commented on tasks/ilo.yml
> +  shell: hponcfg -w conf.txt|grep -i 'Firmware Revision'| awk '{print $8$9}'
Turns out our company has some HPE Gen10 servers! 

The output from the lspci command is this:

<pre>
01:00.0 "System peripheral" "Hewlett-Packard Company" "Integrated Lights-Out Standard Slave Instrumentation & System Support" -r07 "Hewlett Packard Enterprise" "iLO5"`
</pre>

Which based on my awesome bash hacking should output "iLO5"

<pre>
$ echo '01:00.0 "System peripheral" "Hewlett-Packard Company" "Integrated Lights-Out Standard Slave Instrumentation & System Support" -r06 "Hewlett-Packard Company" "iLO4"'|rev|cut -d '"' -f2|rev
iLO5
</pre>

As long as the lspci looks like the above then we should be OK with the existing.

2019-02-06 09:51 UTC, martbhell commented on tasks/ilo.yml
> - - assert: { that: ilo_version is match("ilo4") }
Why remove this? I like to fail early.

2019-03-08 11:44 UTC, oscarkraemer commented
Hi @FLiPp3r90 There has been no response from you in the last month, therefor I will close this PR. We would love to have your changes but it is really important that we understand your changes. So if you have the time feel free to reopen this PR and answer the unanswered questions. 

Cheers,
Oscar

2019-03-08 11:44 UTC, closed without merging

2019-03-08 11:53 UTC, FLiPp3r90 commented
Hi Oscar,

this is okay. In our discussion how to identify the ILO version we decide to live with the old behavior (check pci address).

Mit freundlichen Grüßen

Filip Krahl


T-Systems Multimedia Solutions GmbH
BU AMCS - Document Lifecycle Services
Filip Krahl
System Engineering
Hausanschrift: Riesaer Straße 7, 01129 Dresden
Postanschrift: Postfach 10 02 24, 01072 Dresden
+49 351 2820-7039 (Tel)
+49 351 2820-5112 (Fax)
+49 160 5891262 (Mobil)
E-Mail: filip.krahl@t-systems.com<mailto:filip.krahl@t-systems.com>
Internet: http://www.t-systems-mms.com<http://www.t-systems-mms.de/>

Die gesetzlichen Pflichtangaben finden Sie unter: http://www.t-systems-mms.com/pflichtangaben

Von: Oscar Kraemer <notifications@github.com>
Gesendet: Freitag, 8. März 2019 12:45
An: CSCfi/ansible-role-hp-firmware-upgrade <ansible-role-hp-firmware-upgrade@noreply.github.com>
Cc: Krahl, Filip <Filip.Krahl@t-systems.com>; Mention <mention@noreply.github.com>
Betreff: Re: [CSCfi/ansible-role-hp-firmware-upgrade] add ilo support higher than ilo4 (#24)


Hi @FLiPp3r90<https://github.com/FLiPp3r90> There has been no response from you in the last month, therefor I will close this PR. We would love to have your changes but it is really important that we understand your changes. So if you have the time feel free to reopen this PR and answer the unanswered questions.

Cheers,
Oscar

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/CSCfi/ansible-role-hp-firmware-upgrade/pull/24#issuecomment-470901503>, or mute the thread<https://github.com/notifications/unsubscribe-auth/Ac438V42kfu7Zw2TR5t67SHIMUU8hQEYks5vUk0ygaJpZM4ajfm7>.